### ISSUE TITLE
[0.5.0] Navigation section error

### ISSUE THREAD

**Issue by JahlomP** [pencilblue/pencilblue#856]
Multiple errors occurring
When you create more than one nav menu:

1. Only the last one appears in the navbar
2. When you navigate to /admin/content/navigation it  goes to /admin/content/navigation/new so none of the menu maps appear for reorder or editing

**Comment by JahlomP** [comment]
after furthur investigation, I realised `pb.settings.get('section_map', function(err, sectionMap) {` inside nav_map.js controller is returning null instead of the map of navs. I seem can't find the reason. Can someone help out here? @brianhyder.

**Comment by blakecallens** [comment]
@brianhyder could this be an after-effect of the fix for #846?

**Comment by brianhyder** [comment]
Yes, it is.  It is a botched merge on my part when I pulled it up from master.  If someone has time the line should be updated to ```self.settings.get(...)``` instead.  If not I'll make the change this evening.

**Comment by brianhyder** [comment]
Good catch @JahlomP

**Comment by JahlomP** [comment]
will do it now

**Comment by cchatham** [comment]
@brianhyder @JahlomP we are seeing this error too and I think it is related to large volumes of errors we are seeing in production:

The navigation map is out of sync. Root <long id number> could not be found.

Can we get this fix ASAP?

**Comment by brianhyder** [comment]
@cchatham I merged in a fix for this awhile back. If you are still see errors we're going any additional info you can give us.

**Comment by brianhyder** [comment]
To clarify, I merged the change into 0.5.0

**Comment by cchatham** [comment]
Our 0.5.0 branch of our fork is synced with your 0.5.0 branch and I am running a clean pull of pencilblue locally. When I try to go to navigation management, it always redirects to navigation/new. When I create a new Nav Item sometimes it works and sometimes it doesn't. Attached are log files. nav_issue1.txt shows successful creation but on get nav items, you see the SectionService error that was blowing up on our production server today. nav_issue2.txt is trying to create a nav item that already exists which ends in a fatal error.

[nav_issue.txt](https://github.com/pencilblue/pencilblue/files/75827/nav_issue.txt)
[nav_issue2.txt](https://github.com/pencilblue/pencilblue/files/75828/nav_issue2.txt)

**Comment by cchatham** [comment]
Sorry I totally looked at the wrong thing. Syncing now will let you know if it fixes it.

**Comment by cchatham** [comment]
Okay 100% synced and my navigation is still having issues. New logs attached. Nav_issue is the one creating a nav item that already exists. Nav_issue2 is the creating a new one.

**Comment by cchatham** [comment]
Sorry new logs here
[nav_issue.txt](https://github.com/pencilblue/pencilblue/files/75829/nav_issue.txt)
[nav_issue2.txt](https://github.com/pencilblue/pencilblue/files/75830/nav_issue2.txt)

**Comment by brianhyder** [comment]
Same name issue confirmed and a fix has been pushed to the issue/856 branch.  Still trying to replicate the other issue.

**Comment by brianhyder** [comment]
@cchatham Would you mind emailing me the configuration you guys are using?  I'd like to look over the cache settings in the config.

**Comment by cchatham** [comment]
@brianhyder apparently its just me that is broken. @kylebechtel77 pulled everything down and it is fixed for him.

**Comment by brianhyder** [comment]
Whew... that is good news.  I made some improvements in the branch and will put those into PR today for you guys to look at.  It fixes the out of memory issue that you mentioned and did some cleanup to simplify a couple of things and remove some duplicate code.

**Comment by cchatham** [comment]
@brianhyder THANK YOU! We will pull this sometime today.
